# Generated by Django 6.0.7 on 2026-07-17 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('passenger_name', models.CharField(max_length=255)),
                ('ship_name', models.CharField(max_length=255)),
                ('cabin_type', models.CharField(max_length=100)),
                ('journey_date', models.DateField()),
                ('source_port', models.CharField(max_length=255)),
                ('destination_port', models.CharField(max_length=255)),
                ('total_amount', models.FloatField()),
                ('booking_status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('passenger_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=50)),
                ('nationality', models.CharField(max_length=100)),
                ('passport_number', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('booking_id', models.IntegerField()),
                ('passenger_name', models.CharField(max_length=255)),
                ('amount', models.FloatField()),
                ('payment_method', models.CharField(max_length=100)),
                ('payment_status', models.CharField(max_length=50)),
                ('transaction_id', models.CharField(max_length=255)),
                ('payment_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('schedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('ship_name', models.CharField(max_length=255)),
                ('source_port', models.CharField(max_length=255)),
                ('destination_port', models.CharField(max_length=255)),
                ('departure_date', models.DateField()),
                ('departure_time', models.TimeField()),
                ('arrival_date', models.DateField()),
                ('arrival_time', models.TimeField()),
                ('fare', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('ship_id', models.AutoField(primary_key=True, serialize=False)),
                ('ship_name', models.CharField(max_length=255)),
                ('ship_type', models.CharField(max_length=100)),
                ('capacity', models.IntegerField()),
                ('operator_name', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
    ]
